// Brand logos in /public/img/brands (taken from vitis.ua). alt = brand name.
export const brandNames: Record<string, string> = {
  "louis-roederer": "Louis Roederer",
  "theophile": "Champagne Théophile",
  "domaines-ott": "Domaines Ott",
  "gustave-lorentz": "Gustave Lorentz",
  "chateau-de-tracy": "Château de Tracy",
  "tardieu-laurent": "Tardieu-Laurent",
  "jean-marc-brocard": "Jean-Marc Brocard",
  "la-chablisienne": "La Chablisienne",
  "gitton": "Gitton Sancerre",
  "domaines-schlumberger": "Domaines Schlumberger",
  "lheraud": "Lheraud Cognac",
  "gaston-legrand": "Baron Gaston Legrand",
  "sichel": "Sichel",
  "gcf": "Groupe GCF",
  "campagnola": "Campagnola",
  "livio-felluga": "Livio Felluga",
  "elena-walch": "Elena Walch",
  "cavit": "Cavit",
  "villa-medoro": "Villa Medoro",
  "abbona": "Abbona",
  "la-giustiniana": "La Giustiniana",
  "monte-zovo": "Monte Zovo",
  "mosnel": "Mosnel",
  "antonella-corda": "Antonella Corda",
  "giv": "Gruppo Italiano Vini",
  "nino-negri": "Nino Negri",
  "melini": "Melini",
  "riunite-civ": "Cantine Riunite & Civ",
  "dei": "Dei",
  "le-pupille": "Fattoria Le Pupille",
  "ciacci-piccolomini": "Ciacci Piccolomini d'Aragona",
  "zyme": "Zýmē",
  "masi": "Masi",
  "mazzei": "Mazzei",
  "rock-wines": "Rock Wines",
  "produttori-manduria": "Produttori di Manduria",
  "tenuta-casate": "Tenuta Casate",
  "draga": "Draga",
  "abadia-de-acon": "Abadía de Acón",
  "felix-solis": "Félix Solís Avantis",
  "josep-masachs": "Josep Masachs",
  "anecoop": "Anecoop Bodegas",
  "barbadillo": "Barbadillo",
  "cal-grau": "Cal Grau",
  "enate": "Enate",
  "laus": "Laus",
  "garcia-carrion": "García Carrión",
  "siglo": "Siglo",
  "manzanos": "Bodegas Manzanos",
  "ramos-pinto": "Ramos Pinto",
  "gunderloch": "Gunderloch",
  "errazuriz": "Errázuriz",
  "trapiche": "Trapiche",
  "hallgarten": "Hallgarten & Novum Wines",
  "quoin-rock": "Quoin Rock",
  "man": "MAN Family Wines",
  "kendall-jackson": "Kendall-Jackson",
  "ste-michelle": "Château Ste Michelle",
};

// index = index of the country in dictionary product.countries; the last one (sub-distribution) has no logos
export const brandsByCountry: string[][] = [
  ["louis-roederer", "theophile", "domaines-ott", "gustave-lorentz", "chateau-de-tracy", "la-chablisienne", "gitton", "domaines-schlumberger", "tardieu-laurent", "jean-marc-brocard", "gcf", "lheraud", "sichel", "gaston-legrand"],
  ["campagnola", "livio-felluga", "elena-walch", "cavit", "villa-medoro", "abbona", "la-giustiniana", "monte-zovo", "mosnel", "antonella-corda", "giv", "nino-negri", "melini", "riunite-civ", "dei", "le-pupille", "ciacci-piccolomini", "zyme", "masi", "mazzei", "rock-wines", "produttori-manduria", "tenuta-casate", "draga"],
  ["abadia-de-acon", "felix-solis", "josep-masachs", "anecoop", "barbadillo", "cal-grau", "garcia-carrion", "enate", "siglo", "laus", "manzanos"],
  ["ramos-pinto"],
  ["gunderloch", "gcf"],
  ["errazuriz", "felix-solis", "gcf"],
  ["trapiche", "gcf"],
  ["gcf", "hallgarten"],
  ["quoin-rock", "man", "hallgarten"],
  ["felix-solis", "gcf", "hallgarten"],
  ["kendall-jackson", "gcf", "ste-michelle"],
];
